### ISSUE TITLE
when resize to mobile mode sidebar that was re-create by jquey not work !

### ISSUE THREAD

**Issue by rainstormza** [creativetimofficial/paper-dashboard-angular#1]
when resize to mobile mode sidebar that was re-create by jquey not work !

navbar-right 
- stat , notification , setting

It can use angular 2 binding function (click)="test()" when use normal size (pc)
but when resize to mobile mode function (click)="test()" was gone.

finally, I can use function that I create only pc mode but I can't use that function on mobile mode.

do you know how to fix it ?
thanks
@timcreative

**Comment by alexandru-paduraru** [comment]
@rainstormza this product is [Work in Progress], so it still has some issue that we need to take care before we release it. We will do some further tests to see what is happening when we move to mobile. Can you please let us know which device you tested on? This will help us in reproducing the exact environment that you have.

Best,
Alex

**Comment by rainstormza** [comment]
I tested it in chrome browser (simulator mode for iphone).
I think it doesn't up to device , It broken because when resize jquery find some nav tag and regenerate that tag but function (click) of  angular 2 wasn't regenerate with it, only html tag was regenerate when resize
