### ISSUE TITLE
Toggles

### ISSUE THREAD

**Issue by vadimt2** [creativetimofficial/paper-dashboard-angular#17]
<label class="custom-toggle">
  <input type="checkbox" checked>
  <span class="custom-toggle-slider rounded-circle"></span>
</label>

I can see only a check box

what do i need to install for it to work ?

**Comment by vadimt2** [comment]
TNX, i just updated it to version 8 and it worked
but now i have a different issue:
<label class="custom-toggle">
    <input type="checkbox" checked>
    <span class="custom-toggle-slider rounded-circle" data-label-off="No" data-label-on="Yes"></span>
</label>

I can see only a checkbox

**Comment by rarestoma** [comment]
Hi @vadimt2,

Thank you for working with our products.

Can you please attach an image so I can see clearly what happens?

Thank you,
Rares
