### ISSUE TITLE
sidebar not occur

### ISSUE THREAD

**Issue by yankunsam** [creativetimofficial/paper-dashboard-angular#2]
I just use the sidebar code, but there is blank in  "localhost:4200"

**Comment by chelaruc** [comment]
Hi, @yankunsam! thank you for using our product. Can you give me more information?

Best,
Ciprian

**Comment by ntokozonkosi07** [comment]
the sidebar isn't responsive when running the project on mobile device, please have a look below

![image](https://user-images.githubusercontent.com/5030560/53001101-912a7a00-3432-11e9-9218-ecb26047f99c.png)

**Comment by ntokozonkosi07** [comment]
![image](https://user-images.githubusercontent.com/5030560/53001151-aacbc180-3432-11e9-9cfd-99ed7639dd45.png)

**Comment by chelaruc** [comment]
@ntokozonkosi07 thank you for point this to us. We will update the product these days.
