### ISSUE TITLE
Google Maps not working

### ISSUE THREAD

**Issue by woykan** [creativetimofficial/paper-dashboard-angular#4]
Hi, I am trying to use the maps. I add my API key and it for works from the HTML part. But, when I try to do something from the ts class like new google.maps... I get an error "ReferenceError: google is not defined". I also have "declare var google: any" at the top, but still looks like it does not connect the google classes. Please let me know if you have an idea what is the problem? Thank you.

[maps.component.ts.txt](https://github.com/creativetimofficial/paper-dashboard-angular/files/1692663/maps.component.ts.txt)

**Comment by woykan** [comment]
Update on the issue, seems to be something with the order of loading classes. When I add a setTimeout of half second to the method call it works

**Comment by chelaruc** [comment]
Hi @woykan! Thank you for using our product. Can you move all the code from ngOnInit() to ngAfterViewInit()?

All the best, 
Ciprian

**Comment by woykan** [comment]
Did it, still does not work without a manual delay

**Comment by chelaruc** [comment]
Hey,

Can you send me an archive for testing to ciprian@creative-tim.com?

All the best,
Ciprian

**Comment by Odlir** [comment]
any update on this issue?
