### ISSUE TITLE
Modal with bootstrap doesn't work

### ISSUE THREAD

**Issue by degs098** [creativetimofficial/paper-dashboard-angular#5]
After call a function for open a modal with ngx-bootstrap, he tries to open but immediately get closed.

Heres my code.

HTML:
`<ng-template #modalAudio let-c="close" let-d="dismiss">
    <div class="modal-header">
        <button type="button" class="close" aria-label="Close" (click)="d('Cross click')">
      <span aria-hidden="true">&times;</span>
    </button>
        <h4 class="modal-title">Modal title</h4>
    </div>
    <div class="modal-body">
        <p>One fine body&hellip;</p>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="c('Close click')">Close</button>
    </div>
</ng-template>` 

Component:
`import { Component, OnInit } from '@angular/core';
import { NgbModal, ModalDismissReasons } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'app-audio-library',
  templateUrl: './audio-library.component.html',
  styleUrls: ['./audio-library.component.css'],
})

export class AudioLibraryComponent implements OnInit {

  constructor(
    private modalService: NgbModal
  ) {

  }

  ngOnInit() {

  }

public openAudioModal(modalAudio:any, audio:Audio){
    this.modalService.open(modalAudio)
    .result.then((result) => {
      this.closeResult = Closed with: ${result};
      }, (reason) => {
        this.closeResult = Dismissed ${this.getDismissReason(reason)};
      });
  }

  public getDismissReason(reason: any): string {
    if (reason === ModalDismissReasons.ESC) {
      return 'by pressing ESC';
    } else if (reason === ModalDismissReasons.BACKDROP_CLICK) {
      return 'by clicking on a backdrop';
    } else {
      return with: ${reason};
    }
  }
}`

Thanks for your help!

**Comment by chelaruc** [comment]
Restructured the product.
